sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker

before_intall:
  - docker build -t eddyhum85/docker-react -f Dockerfile.dev .

script:
  - docker run eddyhum85/docker-react npm run test -- --coverage